### ISSUE TITLE
Does it work with hoobs 3.2.10 (node 12.19) ?

### ISSUE THREAD

**Issue by GDeb59** [ximot/homebridge-airly2#1]
Hi,

I installed this plugin on Hoobs (Homebridge Out of a box) from hoobs.org and I have some issues :

 13/11/2020 à 19:24:07 TypeError: Cannot read property 'value' of undefined
    at AirAccessory.updateData (/home/hoobs/.hoobs/node_modules/homebridge-airly2/index.js:73:90)
    at Request._callback (/home/hoobs/.hoobs/node_modules/homebridge-airly2/index.js:51:28)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Any idea about issue ?

**Comment by jerzytraczynski** [comment]
Same issue with homebridge updated to 1.3.0

TypeError: Cannot read property 'value' of undefined
    at AirAccessory.updateData (/usr/local/lib/node_modules/homebridge-airly2/index.js:73:90)
    at Request._callback (/usr/local/lib/node_modules/homebridge-airly2/index.js:51:28)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-airly2/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-airly2/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-airly2/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)

**Comment by ximot** [comment]
Fixed in version 0.1.1
